services:
  app:
    build:
      context: .
    image: weblexai/community-edition:dev
    pull_policy: build

  worker:
    build:
      context: .
    image: weblexai/community-edition:dev
    pull_policy: build

  scheduler:
    build:
      context: .
    image: weblexai/community-edition:dev
    pull_policy: build

  migrate:
    build:
      context: .
    image: weblexai/community-edition:dev
    pull_policy: build

  update-agent:
    build:
      context: .
      dockerfile: docker/update-agent/Dockerfile
    image: weblexai/community-edition-update-agent:dev
    pull_policy: build
