name: CLA

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  cla:
    if: github.event_name == 'pull_request_target' || github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_PAT }}
        with:
          path-to-signatures: ${{ secrets.CLA_SIGNATURES_PATH }}
          path-to-document: https://github.com/${{ github.repository }}/blob/main/docs/cla/INDIVIDUAL.md
          branch: cla-signatures
          allowlist: dependabot[bot]
